import { GenderType } from "@/types/apiEnumTypes";
import { AppointmentEntity } from "../appointments/appointmentTypes";
import { AuditLogEntity } from "../auditLogs/auditLogTypes";
import { BlogEntity } from "../blogs/blogTypes";
import { MessageEntity, QuestionEntity } from "../chat/chatTypes";
import { ConsultantAvailabilityEntity } from "../consultantAvailability/consultantAvailabilityTypes";
import { ConsultantProfileEntity } from "../consultantProfiles/consultantProfileTypes";
import { ContraceptiveReminderEntity } from "../contraceptiveReminders/contraceptiveReminderTypes";
import { DocumentEntity } from "../documents/documentTypes";
import { EmploymentContractEntity } from "../employmentContracts/employmentContractTypes";
import { FeedbackEntity } from "../feedbacks/feedbackTypes";
import { ImageEntity } from "../images/imageTypes";
import { MenstrualCycleEntity } from "../menstrualCycles/menstrualCycleTypes";
import { MenstrualPredictionEntity } from "../menstrualPredictions/menstrualPredictionTypes";
import { NotificationEntity } from "../notifications/notificationTypes";
import { PaymentEntity } from "../payments/paymentTypes";
import { RoleEntity } from "../roles/roleTypes";
import { StiTestProcessEntity } from "../stiTestProcesses/stiTestProcesseTypes";
import { UserPackageSubscriptionEntity } from "../subscriptions/subscriptionTypes";
import { TestResultEntity } from "../testResults/testResultTypes";

export interface UserEntity {
  id: string;
  email: string;
  password?: string;
  googleId?: string;
  firstName: string;
  lastName: string;
  slug: string;
  dateOfBirth: Date | string;
  gender?: GenderType;
  phone?: string;
  address?: string;
  profilePicture?: string;
  isActive: boolean;
  accountLockedUntil?: Date | string;
  loginAttempts: number;
  emailVerified: boolean;
  emailVerificationToken?: string;
  emailVerificationExpires?: Date | string;
  phoneVerified: boolean;
  passwordResetToken?: string;
  passwordResetExpires?: Date | string;
  lastLogin?: Date | string;
  locale: string;
  notificationPreferences: {
    push: boolean;
    email: boolean;
  };
  healthDataConsent: boolean;
  refreshToken?: string;
  deletedByUserId?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  role: RoleEntity;
  consultantProfile?: ConsultantProfileEntity;
  consultantAvailabilities?: ConsultantAvailabilityEntity[];
  appointments: AppointmentEntity[];
  consultantAppointments: AppointmentEntity[];
  authoredBlogs: BlogEntity[];
  reviewedBlogs: BlogEntity[];
  publishedBlogs: BlogEntity[];
  questions: QuestionEntity[];
  messages: MessageEntity[];
  feedbacks: FeedbackEntity[];
  consultantFeedbacks: FeedbackEntity[];
  menstrualCycles: MenstrualCycleEntity[];
  contraceptiveReminders: ContraceptiveReminderEntity[];
  menstrualPredictions: MenstrualPredictionEntity[];
  payments: PaymentEntity[];
  notifications: NotificationEntity[];
  testResults: TestResultEntity[];
  stiTestProcesses: StiTestProcessEntity[];
  documents: DocumentEntity[];
  images: ImageEntity[];
  auditLogs: AuditLogEntity[];
  employmentContracts: EmploymentContractEntity[];
  packageSubscriptions: UserPackageSubscriptionEntity[];
  verifiedConsultantProfiles: ConsultantProfileEntity[];
}
